# Generated by Django 2.0.9 on 2018-10-28 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ORG_name', models.CharField(max_length=100, verbose_name='Organization Name')),
                ('ORG_brief', models.TextField(max_length=250, verbose_name='Who are we ?')),
            ],
        ),
    ]
