# Generated by Django 2.0.9 on 2018-10-28 18:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_organization_org_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='ORG_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organization',
            name='ORG_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='ORG_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_owned', to=settings.AUTH_USER_MODEL),
        ),
    ]
