# Generated by Django 2.0.9 on 2018-11-14 13:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0003_auto_20181028_2051'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='ORG_members',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
