# Generated by Django 2.0.9 on 2018-11-14 13:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_organization_org_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='ORG_members',
            field=models.ManyToManyField(related_name='users', to=settings.AUTH_USER_MODEL),
        ),
    ]
